fix detection of parallel mode
dpasqualin/sfreemap pull request #18
Opened 2021-01-08 15:37 UTC by sam217pa

Hi, 

I've been trying sfreemap, looks great, documentation is very clear.
I ran on an error when trying to reproduce the `map_posterior_distribution` part of the vignette:

```
Error in on_windows() : could not find function "on_windows"
```

I guess this function was superseded by `support_parallel_mode`.

This PR should fix it, along with what I supposed to be a minor logical error.

2021-01-08 15:56 UTC, dpasqualin requested changes

2021-01-08 15:56 UTC, dpasqualin commented on R/sfreemap.R
> +        if (any(parallel, !support_parallel_mode())) {
This is actually correct I think, I want to show a warning if the user requested the parallel mode but it is not available in the operating system. So it should be the same case as before:
```
if (isTRUE(parallel) && support_parallel_mode()) {
```

2021-01-08 15:58 UTC, dpasqualin commented
Hi @sam217pa , thank you very much for your PR!!
I left a comment there, could you please check it and update the PR accordingly? Unfortunately I don't have time to test it now, but I would be happy to merge your PR this weekend and perhaps fix some of the other reported issues.

And please let me know if you manage to use the tool :)

2021-01-08 16:46 UTC, sam217pa commented
my bad ! got it. I think [commit b96](https://github.com/dpasqualin/sfreemap/pull/18/commits/b96e0d73cd3de30de4073b3103ef539a30c86c27) fixes it.

I tested the parallelized function with the corals.trees dataset and it seems to work just fine on macOS, so second commit adds Darwin as list of supported OS.

2021-01-09 13:28 UTC, dpasqualin approved these changes

2021-01-09 13:28 UTC, merged

2021-01-09 13:28 UTC, dpasqualin commented
Thank you very much for your feedback @sam217pa !!